/**
 * The source code in this file is the property of
 * Ripple Systems and is not for redistribution
 * in any form.
 *
 * Source:   $File: //depot/C830AR_TIP/C830AR/transactive/app/pa/PAAgent/src/AbstractPASTable.cpp $
 * @author:  Ripple
 * @version: $Revision: #9 $
 *
 * Last modification: $DateTime: 2025/02/10 22:34:14 $
 * Last modified by:  $Author: limin.zhu $
 *
 */

 ///////////////////////////////////////////////////////////
 //
 //  AbstractPASTable.cpp
 //  Implementation of the Class AbstractPASTable
 //  Generated by Enterprise Architect
 //  Created on:      25-Sep-2003 18:53:34
 //  Original author:
 //
 ///////////////////////////////////////////////////////////
 //  Modification history:
 //
 //
 ///////////////////////////////////////////////////////////

#include "pch.h"
#include "AbstractPASTable.h"
#include "core/data_access_interface/src/LocationAccessFactoryEx.h"
#include "core/message/src/MessagePublicationManager.h"
#include "core/message/types/PAAgentComms_MessageTypes.h"
#include "core/message/src/CommsMessageSender.h"
#include "core/utilities/src/TAAssert.h"
#include "core/utilities/src/DebugUtilEx.h"
#include "core/utilities/src/RunParamsEx.h"
#include "core/utilities/src/MakeNameValuePairsString.h"
#include <boost/range/algorithm.hpp>
#include <mutex>

#define RPARAM_TABLE_590_SIZE   "Table590Size"

using namespace TA_Base_Core;

size_t AbstractPASTable::MAXZONEID      = 0;
size_t AbstractPASTable::MAXSTNID       = TA_Base_Bus::IPAAgentCorbaDef::PA_MAXSTNID;
size_t AbstractPASTable::MAXMODEID      = TA_Base_Bus::IPAAgentCorbaDef::PA_MAXMODEID;
size_t AbstractPASTable::MAXSRCID       = TA_Base_Bus::IPAAgentCorbaDef::PA_MAXSRCID;
size_t AbstractPASTable::MAXMSGSEQ      = TA_Base_Bus::IPAAgentCorbaDef::PA_MAXMSGSEQ;
size_t AbstractPASTable::NBPREREC       = TA_Base_Bus::IPAAgentCorbaDef::PA_NBPREREC;
size_t AbstractPASTable::NBADHOC        = TA_Base_Bus::IPAAgentCorbaDef::PA_NBADHOC;

AbstractPASTable::AbstractPASTable(unsigned long tableNumber)
    : TABLE_NUMBER(tableNumber)
{
    TA_ASSERT(tableNumber != 0, "AbstractPASTable has not been initialised from concrete table instance");

    init();

    BUFFER_SIZE = get_buffer_size(tableNumber);
    LOG_DEBUG("AbstractPASTable(): %s", nvps(tableNumber, BUFFER_SIZE));

    m_buffer = new std::uint8_t[BUFFER_SIZE]{0};

    m_paAgentCommsSender = MessagePublicationManager::getInstance().getCommsMessageSenderPtr(PAAgentComms::Context);
}

void AbstractPASTable::init()
{
    static std::once_flag s_once;

    std::call_once(s_once, []
    {
        MAXZONEID = ThisLocation::is_depot()
            ? TA_Base_Bus::IPAAgentCorbaDef::PA_MAXZONEID_DPT
            : TA_Base_Bus::IPAAgentCorbaDef::PA_MAXZONEID
            ;

        LOG_DEBUG("init(): %s", nvps(MAXZONEID, MAXSTNID, MAXMODEID, MAXSRCID, MAXMSGSEQ, NBPREREC, NBADHOC));
    });
}

size_t AbstractPASTable::get_buffer_size(int tableNumber)
{
    static int t590 = RunParamsEx::get<int>(RPARAM_TABLE_590_SIZE);

    static std::map<int, size_t> s_map  =
    {
        {100,  MAXSTNID * MAXMODEID * MAXZONEID * 1},   // is_depot() ? 102400 : 51200
        {200,  MAXZONEID * 2},                          // is_depot() ? 128 : 64
        {201,  2 + MAXZONEID / 8},                      // is_depot() ? 10 : 6;
        {202,  MAXSRCID * 1},                           // 32;
        {204,  MAXSRCID * MAXZONEID / 8},               // is_depot() ? 256 : 128
        {301,  is_depot() ? 21 : 17},                   // is_depot() ? 21 : 17
        {302,  MAXMSGSEQ * 3},                          // 12
        {303,  is_depot() ? 120 : 104},                 // is_depot() ? 120 : 104
        {350,  12},                                     // 12
        {550,  18},                                     // 18
        {560,  8},                                      // 8
        {570,  1},                                      // 1
        {590,  t590 ? t590 : (is_depot() ? 4 : 2)},     // is_depot() ? 4 : 2
        {603,  NBPREREC * (40 + 1)},                    // 20254
        {604,  NBADHOC * 1},                            // 6
        {610,  84},                                     // 84
        {630,  NBADHOC * 1},                            // 6
        {1200, MAXSTNID * MAXZONEID * 2},               // 3200
        {1201, MAXSTNID * 4 + 2},                       // 202
        {1204, MAXSTNID * MAXSRCID * 4},                // 6400
        {1301, 213},                                    // 213
        {1303, MAXMSGSEQ * 222},                        // 888
        {1610, MAXSTNID * 84},                          // 4200
    };

    TA_ASSERT(s_map.count(tableNumber), "wront table number");
    return s_map[tableNumber];
}

bool AbstractPASTable::is_depot()
{
    return ThisLocation::is_depot();
}

bool AbstractPASTable::is_station()
{
    return ThisLocation::is_station();
}

bool AbstractPASTable::is_station_or_depot()
{
    return is_station() || is_depot();
}

bool AbstractPASTable::is_live(TA_Base_Bus::IPAAgentCorbaDef::ESource source)
{
    static std::vector<TA_Base_Bus::IPAAgentCorbaDef::ESource> s_live_sources =
    {
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_1_PAGING_CONSOLE_MFT_STATION_SO,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_2_PAGING_CONSOLE_MFT_DEPOT_DCO,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_3_PAGING_CONSOLE_MFT_DEPOT_DPSCO,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_4_PAGING_CONSOLE_MFT_OCR_CS,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_5_PAGING_CONSOLE_MFT_OCR_TCO_1,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_6_PAGING_CONSOLE_MFT_OCR_TCO_2,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_7_PAGING_CONSOLE_MFT_OCR_TCO_3,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_8_PAGING_CONSOLE_MFT_OCR_SCO_1,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_9_PAGING_CONSOLE_MFT_OCR_SCO_2,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_10_PAGING_CONSOLE_MFT_OCR_MCO_1,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_11_PAGING_CONSOLE_MFT_OCR_MCO_2,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_12_PAGING_CONSOLE_MFT_OCR_PSCO,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_13_PAGING_CONSOLE_MFT_OCR_TCO_4,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_15_PAGING_CONSOLE_PCP_STATION_1,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_16_PAGING_CONSOLE_PCP_STATION_2,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_27_PAGING_CONSOLE_FCC,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_28_PAGING_CONSOLE_MFT_BDCR_DCO,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_29_PAGING_CONSOLE_MFT_BDCR_PSCO,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_30_PAGING_CONSOLE_BDCR_FCC,
    };

    return boost::count(s_live_sources, source);
}

bool AbstractPASTable::is_live(CORBA::Octet source)
{
    return is_live(static_cast<TA_Base_Bus::IPAAgentCorbaDef::ESource>(source));
}

bool AbstractPASTable::is_bgm(TA_Base_Bus::IPAAgentCorbaDef::ESource source)
{
    static std::vector<TA_Base_Bus::IPAAgentCorbaDef::ESource> s_music_sources =
    {
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_14_BDCR_BGM,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_18_OCR_BGM,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_19_PSC_BGM,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_20_DCR_BGM,
    };

    return boost::count(s_music_sources, source);
}

bool AbstractPASTable::is_bgm(CORBA::Octet source)
{
    return is_bgm(static_cast<TA_Base_Bus::IPAAgentCorbaDef::ESource>(source));
}

bool AbstractPASTable::is_dva(TA_Base_Bus::IPAAgentCorbaDef::ESource source)
{
    static std::vector<TA_Base_Bus::IPAAgentCorbaDef::ESource> s_dva_sources =
    {
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_21_DVA1_SET_A,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_22_DVA1_SET_B_D,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_23_DVA2_SET_A,
        TA_Base_Bus::IPAAgentCorbaDef::PA_SRC_24_DVA2_SET_B_D,
    };

    return boost::count(s_dva_sources, source);
}

bool AbstractPASTable::is_dva(CORBA::Octet source)
{
    return is_dva(static_cast<TA_Base_Bus::IPAAgentCorbaDef::ESource>(source));
}
