/**
 * The source code in this file is the property of
 * Ripple Systems and is not for redistribution
 * in any form.
 *
 * Source:   $File: //depot/C830AR_TIP/C830AR/transactive/app/pa/PAAgent/src/BroadcastWorker.cpp $
 * @author:  Ripple
 * @version: $Revision: #5 $
 *
 * Last modification: $DateTime: 2025/01/08 21:16:53 $
 * Last modified by:  $Author: limin.zhu $
 *
 */
 ///////////////////////////////////////////////////////////
 //
 //  BroadcastWorker.cpp
 //  Implementation of the Class BroadcastWorker
 //  Generated by Enterprise Architect
 //  Created on:      25-Sep-2003 18:53:34
 //  Original author:
 //
 ///////////////////////////////////////////////////////////
 //  Modification history:
 //
 //
 ///////////////////////////////////////////////////////////

#include "pch.h"
#include "BroadcastWorker.h"
#include "AbstractBroadcast.h"
#include "AbstractBroadcastCircularList.h"
#include "CachedConfig.h"
#include "core/utilities/src/TAAssert.h"
#include "core/utilities/src/DebugUtilEx.h"
#include "core/utilities/src/MakeNameValuePairsString.h"
#include "core/message/src/MessagePublicationManager.h"
#include "core/message/src/StateUpdateMessageSender.h"
#include "core/message/types/PAAgentStateUpdate_MessageTypes.h"
#include "core/message/types/PAAgentComms_MessageTypes.h"
#include "core/message/src/CommsMessageSender.h"
#include "core/message/src/MessageSubscriptionManager.h"
#include <time.h>

using namespace TA_Base_Core;

namespace TA_IRS_App
{
    // ExceptionChecked
    BroadcastWorker::BroadcastWorker()
        : Thread("BroadcastWorker"),
        m_allBroadcasts(NULL),
        m_isRunning(false),
        m_paAgentCommsSender(NULL),
        m_trainAgentSubscriber(),
        m_stateUpdateMessageSender(NULL),
        m_isEnabled(false),
        m_cachedConfigInstance(NULL),
        m_isChangingToControlMode(false)
    {
        FUNCTION_ENTRY("Constructor");

        m_allBroadcasts = AbstractBroadcastCircularList::getInstance();

        m_cachedConfigInstance = CachedConfig::getInstance();

        m_paAgentCommsSender = MessagePublicationManager::getInstance().getCommsMessageSenderPtr(PAAgentComms::Context);

        m_stateUpdateMessageSender = MessagePublicationManager::getInstance().getStateUpdateMessageSenderPtr(PAAgentStateUpdate::Context);

        FUNCTION_EXIT;
    }

    // ExceptionChecked
    BroadcastWorker::~BroadcastWorker()
    {
        FUNCTION_ENTRY("Destructor");
        TA_ASSERT(!m_isRunning, "Deleting a running thread");

        m_trainAgentSubscriber.unsubscribe();

        m_allBroadcasts = NULL;

        FUNCTION_EXIT;
    }

    // ExceptionChecked
    void BroadcastWorker::run()
    {
        FUNCTION_ENTRY("run");

        m_trainAgentSubscriber.subscribe();
        m_isRunning = true;

        while (m_isRunning)
        {
            if (!m_isChangingToControlMode)
            {
                try
                {
                    // This call will block if nothing is there
                    processNextBroadcast(m_allBroadcasts->getNext());
                }
                catch (const std::exception& e)
                {
                    // Not expecting any failures...
                    LOG_EXCEPTION_CATCH(SourceInfo, "std::exception", e.what());
                }
                catch (...)
                {
                    // Not expecting any failures...
                    LOG_EXCEPTION_CATCH(SourceInfo, "Unknown exception", "Unknown reason");
                }
            }
            else
            {
                Thread::sleep(10000);
            }

            Thread::sleep(m_cachedConfigInstance->getWorkerThreadsSleepTimeInMSecs());
        }

        m_trainAgentSubscriber.unsubscribe();

        FUNCTION_EXIT;
    }

    // ExceptionChecked
    void BroadcastWorker::terminate()
    {
        FUNCTION_ENTRY("terminate");

        m_isRunning = false;
        // Wake up the semaphore so we can exit the run loop
        m_allBroadcasts->unBlockList();

        FUNCTION_EXIT;
    }

    void BroadcastWorker::processNextBroadcast(AbstractBroadcast* broadcast)
    {
        if (!broadcast)
        {
            return;
        }

        if (!m_isEnabled)
        {
            return;
        }

        LOG_SCOPE(broadcast->getBroadcastId(), st::enum_to_string_value(broadcast->getBroadcastState()));

        switch (broadcast->getBroadcastState())
        {
            case TA_Base_Bus::IPAAgentCorbaDef::Creation:
                broadcast->setBroadcastState(TA_Base_Bus::IPAAgentCorbaDef::Execution);
                sendProgressUpdateIfChanged(broadcast);
                break;

            case TA_Base_Bus::IPAAgentCorbaDef::Execution:
                broadcast->execute();
                sendProgressUpdateIfChanged(broadcast);
                break;

            case TA_Base_Bus::IPAAgentCorbaDef::Runtime:
                broadcast->updateRuntimeState();
                sendProgressUpdateIfChanged(broadcast);
                break;

            case TA_Base_Bus::IPAAgentCorbaDef::Termination:
                broadcast->terminate();
                sendProgressUpdateIfChanged(broadcast);
                break;

            case TA_Base_Bus::IPAAgentCorbaDef::PendingRemoval:
                if (shouldRemoveBroadcast(broadcast))
                {
                    deleteBroadcast(broadcast);
                    broadcast = NULL;
                }

                break;

            default:
                // CorruptInternalStateData - we will dispose of this broadcast
                deleteBroadcast(broadcast);
                broadcast = NULL;
                break;
        }
    }

    void BroadcastWorker::deleteBroadcast(AbstractBroadcast* broadcast)
    {
        LOG_SCOPE("BroadcastWorker::deleteBroadcast");

        TA_ASSERT(broadcast, "broadcast is NULL");

        m_allBroadcasts->remove(broadcast);

        // Notify all PA Managers
        TA_Base_Bus::IPAAgentCorbaDef::CurrentBroadcastsUpdateData updateData;

        // Note: string members will make a deep copy from a const char*
        updateData.fromBroadcastId = broadcast->getBroadcastId().c_str();
        updateData.toBroadcastId   = CORBA::string_dup("");
        updateData.broadcastType   = broadcast->getBroadcastType();
        updateData.sessionId       = broadcast->getSessionId().c_str();

        PasHelpers::instance().sendCurrentBroadcastsUpdate(updateData);
        PasHelpers::instance().sendPAAgentRemovedBroadcastUpdate(broadcast->getBroadcastId().c_str());

        delete broadcast;
        broadcast = NULL;
    }

    bool BroadcastWorker::shouldRemoveBroadcast(AbstractBroadcast* broadcast)
    {
        if (broadcast->getIsEventTriggered())
        {
            return true;
        }

        if (broadcast->getIsTaggedForRemoval())
        {
            return true;
        }

        switch (broadcast->getBroadcastType())
        {
            case TA_Base_Bus::IPAAgentCorbaDef::StationMusic:

                // All music (and music termination) broadcasts are removed ASAP.
            case TA_Base_Bus::IPAAgentCorbaDef::StationRecording:
                // Same goes for the recording broadcast as there is no option to
                // retry.
                return true;

            case TA_Base_Bus::IPAAgentCorbaDef::StationDva:
            case TA_Base_Bus::IPAAgentCorbaDef::StationLive:
            case TA_Base_Bus::IPAAgentCorbaDef::TrainDva:
            case TA_Base_Bus::IPAAgentCorbaDef::TrainLive:

                // In the case of live broadcasts, these should be removed as soon as
                // the operator closes the status dialog.  In the odd occurrence that
                // the PA Manager crashes, the terminated live broadcast will be
                // cleaned up in 24 hours regardless.
            {
                time_t now = time(NULL);
                time_t howOld = now - broadcast->getLastUpdate();

                if (howOld > m_cachedConfigInstance->getKeepTerminatedBroadcastsInSecs())
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }

            default:
                // CorruptInternalStateData - we will dispose of this broadcast
                return true;
        }

        return true;
    }

    void BroadcastWorker::sendProgressUpdateIfChanged(AbstractBroadcast* broadcast)
    {
        LOG_SCOPE("BroadcastWorker::sendProgressUpdateIfChanged");

        if (!broadcast->getHasProgressReportChanged())
        {
            return;
        }

        if (broadcast->getIsEventTriggered())
        {
            // No updates for event triggered broadcasts required
            return;
        }

        LOG_INFO("sendProgressUpdateIfChanged(): Sending BroadcastProgressUpdate message for broadcastId=%s", broadcast->getBroadcastId());

        CORBA::Any data;
        NameValuePair nvp(TA_Base_Bus::IPAAgentCorbaDef::BROADCAST_ID_FILTER_STRING, broadcast->getBroadcastId());

        std::vector<NameValuePair*> extraFilterableData;
        extraFilterableData.push_back(&nvp);

        auto report = broadcast->getProgressReportCopy();
        LOG_DEBUG("sendProgressUpdateIfChanged(): %s", nvps(*report));
        data <<= report;

        // Send Comms message for PA Managers
        m_paAgentCommsSender->sendCommsMessage(PAAgentComms::BroadcastProgressUpdate,                  // Context::Type
                                               m_cachedConfigInstance->getAgentKey(),                  // EntityKey
                                               data,                                                   // Data
                                               m_cachedConfigInstance->getAgentSubsystemKey(),         // Subsystem
                                               m_cachedConfigInstance->getAgentLocationKey(),          // LocationKey
                                               &extraFilterableData);                                  // BroadcastId

        // Send State update message for PA Agents
        m_stateUpdateMessageSender->sendStateUpdateMessage(PAAgentStateUpdate::PAAgentBroadcastProgressUpdate,
                                                           0,
                                                           m_cachedConfigInstance->getAgentName(),
                                                           data);

        // reset the flag
        broadcast->setHasProgressReportChanged(false);
    }
}
