/**
 * The source code in this file is the property of
 * Ripple Systems and is not for redistribution
 * in any form.
 *
 * Source:   $File: //depot/C830AR_TIP/C830AR/transactive/app/pa/PAAgent/src/BroadcastWorker.h $
 * @author:  Ripple
 * @version: $Revision: #3 $
 *
 * Last modification: $DateTime: 2024/12/17 16:14:02 $
 * Last modified by:  $Author: limin.zhu $
 *
 */
 ///////////////////////////////////////////////////////////
 //
 //  BroadcastWorker.h
 //  Implementation of the Class BroadcastWorker
 //  Generated by Enterprise Architect
 //  Created on:      25-Sep-2003 18:53:34
 //  Original author:
 //
 ///////////////////////////////////////////////////////////
 //  Modification history:
 //
 //
 ///////////////////////////////////////////////////////////

#pragma once
#include "app/pa/PAAgent/src/TrainAgentSubscriber.h"
#include "core/threads/src/Thread.h"
#include <string>

class CachedConfig;

namespace TA_Base_Core
{
    class CommsMessageSender;
    using CommsMessageSenderPtr = std::shared_ptr<CommsMessageSender>;
    class StateUpdateMessageSender;
    using StateUpdateMessageSenderPtr = std::shared_ptr<StateUpdateMessageSender>;
}

namespace TA_IRS_App
{
    class AbstractBroadcastCircularList;
    class AbstractBroadcast;

    class BroadcastWorker : public TA_Base_Core::Thread
    {
    public:

        BroadcastWorker();
        virtual ~BroadcastWorker();

        virtual void run();
        virtual void terminate();

        void enable()
        {
            // Implicitly threadsafe
            m_isEnabled = true;
        }

        void disable()
        {
            // Implicitly threadsafe
            m_isEnabled = false;
        }

        void setModeChangingFlag(bool flag)
        {
            m_isChangingToControlMode = flag;
        }

        void processNextBroadcast(AbstractBroadcast* broadcast);

    protected:

        void deleteBroadcast(AbstractBroadcast* broadcast);
        bool shouldRemoveBroadcast(AbstractBroadcast* broadcast);
        void sendProgressUpdateIfChanged(AbstractBroadcast* broadcast);

        volatile bool                       m_isRunning;
        volatile bool                       m_isEnabled;
        volatile bool                       m_isChangingToControlMode;
        AbstractBroadcastCircularList* m_allBroadcasts;
        TA_Base_Core::CommsMessageSenderPtr m_paAgentCommsSender;
        TA_Base_Core::StateUpdateMessageSenderPtr m_stateUpdateMessageSender;
        TrainAgentSubscriber                m_trainAgentSubscriber;
        CachedConfig* m_cachedConfigInstance;

    private:

        BroadcastWorker(const BroadcastWorker& theBroadcastWorker);
    };
}
