/**
 * The source code in this file is the property of
 * Ripple Systems and is not for redistribution
 * in any form.
 *
 * Source:   $File: //depot/C830AR_TIP/C830AR/transactive/app/pa/PAAgent/src/FireCountdownAckMonitor.cpp $
 * @author:  Ripple
 * @version: $Revision: #4 $
 *
 * Last modification: $DateTime: 2024/12/18 11:16:51 $
 * Last modified by:  $Author: limin.zhu $
 *
 */
 ///////////////////////////////////////////////////////////
 //
 //  FireCountdownAckMonitor.cpp
 //  Implementation of the Class FireCountdownAckMonitor
 //  Generated by Enterprise Architect
 //  Created on:      25-Sep-2003 18:53:34
 //  Original author:
 //
 ///////////////////////////////////////////////////////////
 //  Modification history:
 //
 //
 ///////////////////////////////////////////////////////////

#include "pch.h"
#include "Table570.h"
#include "CachedConfig.h"
#include "FireCountdownAckMonitor.h"
#include "bus/scada/datapoint_library/src/DataPoint.h"
#include "core/utilities/src/TAAssert.h"
#include "core/utilities/src/DebugUtilEx.h"
#include "core/exceptions/src/ScadaProxyException.h"

namespace TA_IRS_App
{
    FireCountdownAckMonitor::FireCountdownAckMonitor(Table570& table570)
        : m_table570(table570),
        m_proxyFactory(TA_Base_Bus::ScadaProxyFactory::getInstance()),
        m_isAlarmAcked(false),
        m_isEnabled(false)
    {
        FUNCTION_ENTRY("Constructor");

        TA_Base_Bus::DataPoint* dp = CachedConfig::getInstance()->getFireCountdownActiveDP();

        if (dp)
        {
            try
            {
                m_proxyFactory.createDataPointProxy(dp->getEntityKey(), *this, m_fireCountdownProxy);
            }
            catch (TA_Base_Core::ScadaProxyException)
            {
                LOG_ERROR("Caught a ScadaProxyException when calling createDataPointProxy.");
            }
            catch (...)
            {
                LOG_ERROR("Caught an Unknown Exception when calling createDataPointProxy.");
            }
        }
        else
        {
            LOG_ERROR("Cannot find FireCountdownActive datapoint in order to register for acknowledgement notifications.");
        }

        FUNCTION_EXIT;
    }

    // ExceptionChecked
    FireCountdownAckMonitor::~FireCountdownAckMonitor()
    {
        FUNCTION_ENTRY("Destructor");

        //2008-07-18 clear DataPointProxySmartPtr
        //m_fireCountdownProxy->reset();

        TA_Base_Bus::ScadaProxyFactory::removeInstance();

        FUNCTION_EXIT;
    }

    void FireCountdownAckMonitor::setControl(bool isOnStartup)
    {
        m_isEnabled = true;
        m_proxyFactory.setProxiesToControlMode();
    }

    void FireCountdownAckMonitor::setMonitor(bool isOnStartup)
    {
        m_isEnabled = false;
        m_proxyFactory.setProxiesToMonitorMode();
    }

    void FireCountdownAckMonitor::processEntityUpdateEvent(unsigned long entityKey, TA_Base_Bus::ScadaEntityUpdateType updateType)
    {
        LOG_SCOPE("FireCountdownAckMonitor::processEntityUpdateEvent");

        if (!m_isEnabled)
        {
            LOG_INFO("Skipping operation in operation mode");
            return;
        }

        if (updateType != TA_Base_Bus::ValueStateUpdate &&
            updateType != TA_Base_Bus::AlarmSummaryUpdate && //limin++, TD20740
            updateType != TA_Base_Bus::AckSummaryUpdate)    //limin++, TD20740
        {
            LOG_DEBUG("Received a proxy update, but it is not value update, ingored.");
            return;
        }

        bool isAcked = false;

        try
        {
            isAcked = (m_fireCountdownProxy)->getAlarmAckState() == TA_Base_Bus::ScadaAlarmAck ||
                (m_fireCountdownProxy)->getAlarmAckState() == TA_Base_Bus::ScadaAlarmNotPresent;
        }
        catch (TA_Base_Core::ScadaProxyException)
        {
            LOG_ERROR("Caught a ScadaProxyException when calling getAlarmAckState.");
        }
        catch (...)
        {
            LOG_ERROR("Caught an Unknown Exception when calling getAlarmAckState.");
        }

        if (m_isAlarmAcked == isAcked)
        {
            LOG_DEBUG("Received a datapoint value update, but alarm ack state is not changed, ingored.");
            return;
        }

        m_isAlarmAcked = isAcked;

        if (!m_isAlarmAcked)
        {
            LOG_INFO("Ignoring alarm which is not acknowledged");
            return;
        }

        LOG_INFO("Received FireCountdownActive alarm acknowledgement for entitykey %u", entityKey);

        //  m_theDatapoints.setCongestionAppliedGivenEntityKey(currentAlarmState.getAlarmEntityKey(), true);
        // TD18294
        if (!m_table570.isOnFireAlarmState())
        {
            LOG_INFO("FEPC is not on Fire Alarm state, ingored.");
            return;
        }

        // TD18294

        try
        {
            m_table570.resetFireAlarmStatusAndWrite();
        }
        catch (...)
        {
            LOG_ERROR("Failed to abort FireCountdown.");
        }
    }
}
