/**
 * The source code in this file is the property of
 * Ripple Systems and is not for redistribution
 * in any form.
 *
 * Source:   $File: //depot/C830AR_TIP/C830AR/transactive/app/pa/PAAgent/src/Table201.cpp $
 * @author:  Ripple
 * @version: $Revision: #5 $
 *
 * Last modification: $DateTime: 2025/02/14 12:19:11 $
 * Last modified by:  $Author: limin.zhu $
 *
 */
 ///////////////////////////////////////////////////////////
 //
 //  Table201.cpp
 //  Implementation of the Class Table201
 //  Generated by Enterprise Architect
 //  Created on:      25-Sep-2003 18:53:34
 //  Original author:
 //
 ///////////////////////////////////////////////////////////
 //  Modification history:
 //
 //
 ///////////////////////////////////////////////////////////

#include "pch.h"
#include "Table201.h"
#include "PasHelpers.h"
#include "PASConnection.h"
#include "PasTableManager.h"
#include "core/data_access_interface/src/LocationAccessFactoryEx.h"
#include "core/utilities/src/TAAssert.h"
#include "core/utilities/src/DebugUtilEx.h"
#include <ace/ACE.h>

using namespace TA_Base_Core;

const size_t TABLE_201_SOURCE_ID_OFFSET         = 0;
const size_t TABLE_201_ANNOUNCE_ID_OFFSET       = 1;
const size_t TABLE_201_LOCAL_COVERAGE_OFFSET    = 2;

namespace TA_IRS_App
{
    Table201::Table201(TA_IRS_Bus::Scheduler& socketScheduler,
                       TA_IRS_Bus::Scheduler& processScheduler,
                       IPasEventSource& eventSource)
        : AbstractWriteablePASTable(201)
        , m_socketScheduler(socketScheduler)
        , m_processScheduler(processScheduler)
        , m_pasEventSource(eventSource)
    {
        FUNCTION_ENTRY("Constructor");
        FUNCTION_EXIT;
    }

    void Table201::setTableDataAndWrite(CORBA::Octet sourceId,
                                        CORBA::Octet announceId,
                                        const TA_Base_Bus::IPAAgentCorbaDef::ZoneCoverage& zones)
        //throw ( TA_Base_Core::PasWriteErrorException, TA_Base_Core::PasConnectionException, TA_Base_Core::CachedMappingNotFoundException )
    {
        LOG_SCOPE("Table201::setTableDataAndWrite");

        ACE_Future<int> future;
        WriteTable201* event = new WriteTable201(*this,
                                                 future,
                                                 sourceId,
                                                 announceId,
                                                 zones,
                                                 m_socketScheduler,
                                                 m_processScheduler,
                                                 m_pasEventSource);
        addWriteEvent(*event);
        m_socketScheduler.post(event);

        int retVal = -1;
        ACE_Time_Value tv(10, 0);
        tv += ACE_OS::gettimeofday();

        if (-1 == future.get(retVal, &tv))
        {
            char msg[100] = {0};
            sprintf(msg, "Timeout on write operation on table %d", TABLE_NUMBER);
            TA_THROW(TA_Base_Core::PasWriteErrorException(retVal, msg));
        }

        if (retVal)
        {
            char msg[100] = {0};
            sprintf(msg, "Write operation on table %d returned an error state %d", TABLE_NUMBER, retVal);
            TA_THROW(TA_Base_Core::PasWriteErrorException(retVal, msg));
        }
    }

    WriteTable201::WriteTable201(Table201& table,
                                 ACE_Future<int>& future,
                                 CORBA::Octet sourceId,
                                 CORBA::Octet announceId,
                                 const TA_Base_Bus::IPAAgentCorbaDef::ZoneCoverage& zones,
                                 TA_IRS_Bus::Scheduler& socketScheduler,
                                 TA_IRS_Bus::Scheduler& processScheduler,
                                 IPasEventSource& eventSource)
        : PASWriteEvent(table, future, socketScheduler, processScheduler, eventSource)
        , m_table(table)
        , m_sourceId(sourceId)
        , m_announceId(announceId)
        , m_zones(zones)
    {
    }

    WriteTable201::WriteTable201(ACE_Time_Value timeToExpire,
                                 Table201& table,
                                 ACE_Future<int>& future,
                                 CORBA::Octet sourceId,
                                 CORBA::Octet announceId,
                                 const TA_Base_Bus::IPAAgentCorbaDef::ZoneCoverage& zones,
                                 TA_IRS_Bus::Scheduler& socketScheduler,
                                 TA_IRS_Bus::Scheduler& processScheduler,
                                 IPasEventSource& eventSource)
        : PASWriteEvent(timeToExpire, table, future, socketScheduler, processScheduler, eventSource)
        , m_table(table)
        , m_sourceId(sourceId)
        , m_announceId(announceId)
        , m_zones(zones)
    {
    }

    void WriteTable201::writeTable()
    {
        LOG_SCOPE("WriteTable201::writeTable");

        // ReEntrant as this will also be guarded in the write() call.
        ThreadGuard guard(m_table.m_lock);

        PasHelpers::instance().set8bit(m_table.m_buffer, TABLE_201_SOURCE_ID_OFFSET, m_sourceId);
        PasHelpers::instance().set8bit(m_table.m_buffer, TABLE_201_ANNOUNCE_ID_OFFSET, m_announceId);

        if (is_depot())
        {
            auto localCoverageBitmap = PasHelpers::instance().coverageToLocalCoverageBitmap<std::uint64_t>(m_zones);

            if (AbstractPASTable::is_bgm(m_sourceId))
            {
                localCoverageBitmap = UINT64_MAX;
            }

            PasHelpers::instance().set64bit(m_table.m_buffer, TABLE_201_LOCAL_COVERAGE_OFFSET, localCoverageBitmap);
        }
        else
        {
            auto localCoverageBitmap = PasHelpers::instance().coverageToLocalCoverageBitmap<std::uint32_t>(m_zones);

            if (AbstractPASTable::is_bgm(m_sourceId))
            {
                localCoverageBitmap = UINT32_MAX;
            }

            PasHelpers::instance().set32bit(m_table.m_buffer, TABLE_201_LOCAL_COVERAGE_OFFSET, localCoverageBitmap);
        }

        m_future.set(PASConnection::getInstance()->writeTable(m_table.TABLE_NUMBER,
                                                              m_table.m_buffer,
                                                              m_table.BUFFER_SIZE));
    }

    PASWriteEvent* WriteTable201::recreateEvent(ACE_Time_Value timeToExpire)
    {
        return new WriteTable201(timeToExpire,
                                 m_table,
                                 m_future,
                                 m_sourceId,
                                 m_announceId,
                                 m_zones,
                                 m_socketScheduler,
                                 m_processScheduler,
                                 m_pasEventSource);
    }
}
