/**
 * The source code in this file is the property of
 * Ripple Systems and is not for redistribution
 * in any form.
 *
 * Source:   $File: //depot/C830AR_TIP/C830AR/transactive/app/pa/PAAgent/src/Table204.cpp $
 * @author:  Ripple
 * @version: $Revision: #8 $
 *
 * Last modification: $DateTime: 2025/06/24 11:25:13 $
 * Last modified by:  $Author: limin.zhu $
 *
 */
 ///////////////////////////////////////////////////////////
 //
 //  Table204.cpp
 //  Implementation of the Class Table204
 //  Generated by Enterprise Architect
 //  Created on:      25-Sep-2003 18:53:34
 //  Original author:
 //
 ///////////////////////////////////////////////////////////
 //  Modification history:
 //
 //
 ///////////////////////////////////////////////////////////

#include "pch.h"
#include "Table204.h"
#include "PasHelpers.h"
#include "PasTableManager.h"
#include "PASConnection.h"
#include "core/data_access_interface/src/LocationAccessFactoryEx.h"
#include "core/utilities/src/TAAssert.h"
#include "core/utilities/src/DebugUtilEx.h"

using namespace TA_Base_Core;

namespace
{
    size_t TABLE_204_RECORD_SIZE = 4;
}

namespace TA_IRS_App
{
    // ExceptionChecked
    Table204::Table204()
        : AbstractPASTable(204)
    {
        FUNCTION_ENTRY("Constructor");

        if (is_depot())
        {
            TABLE_204_RECORD_SIZE = 8;
        }

        FUNCTION_EXIT;
    }

    void Table204::processRead()
    {
        // No processing required
    }

    TA_Base_Bus::IPAAgentCorbaDef::ZoneCoverage Table204::getLocalCoverage(unsigned int sourceId)
        //throw ( TA_Base_Core::PasConnectionException )
    {
        TA_ASSERT(sourceId <= MAXSRCID, "sourceId out of bounds");

        ThreadGuard guard(m_lock);

        unsigned long offset = TABLE_204_RECORD_SIZE * (sourceId - 1);

        if (is_depot())
        {
            auto localCoverageBitmap = PasHelpers::instance().get64bit(m_buffer, offset);
            return PasHelpers::instance().localCoverageBitmapToCoverage(localCoverageBitmap,
                                                                        CachedConfig::getInstance()->getAgentLocationKey());
        }
        else
        {
            auto localCoverageBitmap = PasHelpers::instance().get32bit(m_buffer, offset);
            return PasHelpers::instance().localCoverageBitmapToCoverage(localCoverageBitmap,
                                                                        CachedConfig::getInstance()->getAgentLocationKey());
        }
    }

    ReadTable204::ReadTable204(Table204& table,
                               Table560& table560,
                               TA_IRS_Bus::Scheduler& socketScheduler,
                               TA_IRS_Bus::Scheduler& processScheduler,
                               IPasEventSource& eventSource)
        : PASReadEvent(socketScheduler, processScheduler, eventSource)
        , m_table(table)
        , m_table560(table560)
    {
    }

    void ReadTable204::readTable()
    {
        LOG_SCOPE("ReadTable204::readTable");

        ThreadGuard guard(m_table.m_lock);
        PASConnection::getInstance()->readTable(m_table.TABLE_NUMBER,
                                                m_table.m_buffer,
                                                m_table.BUFFER_SIZE);

        PasTableReadCounter::instance().increase(m_table.TABLE_NUMBER);

        m_table560.resetFlags(this,
                              Table560::TABLE_560_TABLE_204_FLAG_A_BIT_OFFSET,
                              Table560::TABLE_560_TABLE_204_FLAG_B_BIT_OFFSET);
    }
}
