/**
 * The source code in this file is the property of
 * Ripple Systems and is not for redistribution
 * in any form.
 *
 * Source:   $File: //depot/C830AR_TIP/C830AR/transactive/app/pa/PAAgent/src/Table1200.cpp $
 * @author:  Ripple
 * @version: $Revision: #9 $
 *
 * Last modification: $DateTime: 2025/06/24 11:25:13 $
 * Last modified by:  $Author: limin.zhu $
 *
 */
 ///////////////////////////////////////////////////////////
 //
 //  Table1200.cpp
 //  Implementation of the Class Table1200
 //  Generated by Enterprise Architect
 //  Created on:      25-Sep-2003 18:53:34
 //  Original author:
 //
 ///////////////////////////////////////////////////////////
 //  Modification history:
 //
 //
 ///////////////////////////////////////////////////////////

#include "pch.h"
#include "Table1200.h"
#include "PasHelpers.h"
#include "PasTableManager.h"
#include "PASConnection.h"
#include "CachedConfig.h"
#include "Table202.h"
#include "Table302.h"
#include "Table1303.h"
#include "bus/scada/datapoint_library/src/DataPoint.h"
#include "bus/pa/cachedmaps/src/CachedMaps.h"
#include "core/utilities/src/TAAssert.h"
#include "core/utilities/src/DebugUtilEx.h"
#include <time.h>

using namespace boost::describe::operators;
using namespace TA_Base_Core;
using namespace TA_IRS_Bus;

namespace TA_IRS_App
{
    Table1200::Table1200(Table202* table202, Table302* table302, Table1303* table1303)
        : AbstractPASTable(1200)
    {
        FUNCTION_ENTRY("Constructor");

        m_cachedMapsInstance = CachedMaps::getInstance();

        m_stationStatuses.resize(MAXSTNID);

        for (int stationId = 0; stationId < MAXSTNID; ++stationId)
        {
            m_stationStatuses[stationId].resize(MAXZONEID);
        }

        m_table202 = table202;
        m_table302 = table302;
        m_table1303 = table1303;

        FUNCTION_EXIT;
    }

    // TD 17013
    void Table1200::setInitalThreadValue(bool initialThreadValue)
    {
        m_initialThread = initialThreadValue;
    }

    // TD 17013

    // TD16749
    void Table1200::processRead()
    {
        LOG_SCOPE("Table1200::processRead");

        ThreadGuard guard(m_lock);

        unsigned long absoluteZoneId = 1;

        for (int stationId = 0; stationId < MAXSTNID; ++stationId)
        {
            LOG_SCOPE(boost::format("STATION[%d]") % (stationId + 1));

            for (int zoneId = 0; zoneId < MAXZONEID; ++zoneId, ++absoluteZoneId)
            {
                LOG_SCOPE(boost::format("ZONE[%d]") % (zoneId + 1));

                // zone data is expected to be in the following format
                //
                // Bit: 15 14 13 12 11 10 09 08 07  06 05 04 03 02 01 00
                //      |_____________________|  |  |__________________|
                //                |              |            |
                //           Source Id        Status       Priority
                //
                std::uint16_t zoneData = PasHelpers::instance().get16bit(m_buffer, (absoluteZoneId - 1) * 2);

                bool isNeedUpdateSourceId = false;
                bool isNeedUpdateStatus   = false;
                bool isNeedUpdatePriority = false;

                auto sourceId = static_cast<TA_Base_Bus::IPAAgentCorbaDef::ESource>(zoneData >> 8);
                bool status = (zoneData & (0x0080)) != 0;
                CORBA::Octet priority = static_cast<CORBA::Octet>(zoneData & (0x007f));

                auto zoneStatus = ZoneStatus{sourceId, status, priority};
                auto& oldZoneStatus = m_stationStatuses[stationId][zoneId];
                LOG_DEBUG_IF(zoneStatus != oldZoneStatus, "%s", nvps(oldZoneStatus, zoneStatus));

                if (oldZoneStatus.m_sourceId != sourceId)
                {
                    oldZoneStatus.m_sourceId = sourceId;
                    isNeedUpdateSourceId = true;
                }

                if (oldZoneStatus.m_status != status)
                {
                    oldZoneStatus.m_status = status;
                    isNeedUpdateStatus = true;
                }

                if (oldZoneStatus.m_priority != priority)
                {
                    oldZoneStatus.m_priority = priority;
                    isNeedUpdatePriority = true;
                }

                LOG_DEBUG_IF(zoneStatus != oldZoneStatus, "%s", nvps(isNeedUpdateSourceId, isNeedUpdateStatus, isNeedUpdatePriority));

                // The datapoints will only update if the DataPointState has changed
                // (with the exception of just a timestamp change).  Therefore to
                // simplify the code, we update the datapoint regardless.

                if (isNeedUpdateSourceId || m_initialThread) // TD17013
                {
                    TA_Base_Bus::DataPoint* liveDp   = m_cachedMapsInstance->getLiveDataPointFromZoneId(absoluteZoneId);
                    TA_Base_Bus::DataPoint* cyclicDp = m_cachedMapsInstance->getCyclicDataPointFromZoneId(absoluteZoneId);
                    TA_Base_Bus::DataPoint* musicDp  = m_cachedMapsInstance->getMusicDataPointFromZoneId(absoluteZoneId);
                    LOG_ERROR_IF_NOT(liveDp, "processRead(): can not find live datapoitn for station id %d, zone id = %d", stationId + 1, absoluteZoneId);
                    LOG_ERROR_IF_NOT(cyclicDp, "processRead(): can not find cyclic datapoitn for zone id %d", stationId + 1, absoluteZoneId);
                    LOG_ERROR_IF_NOT(musicDp, "processRead(): can not find music datapoitn for zone id %d", stationId + 1, absoluteZoneId);

                    bool isLive = is_live(sourceId);
                    bool isMusic = is_bgm(sourceId);
                    bool isDva = is_dva(sourceId);
                    bool isCyclic = false;

                    if (isDva)
                    {
                        CORBA::Octet announcementId = m_table202->getAnnounceId(sourceId);
                        unsigned int sequenceId = m_table302->getSequenceId(announcementId);
                        isCyclic = m_table1303->isMessageSequenceCyclic(sequenceId);
                    }

                    LOG_DEBUG_IF(isLive || isMusic || isDva, "%s", nvps(isLive, isMusic, isDva, isCyclic));

                    if (liveDp)
                    {
                        TA_Base_Bus::DpValue dpValue(liveDp->getDataPointDataType(),
                                                     liveDp->getEnumLabelsMap(),
                                                     liveDp->getBooleanLabels());
                        dpValue.setBoolean(isLive);
                        TA_Base_Bus::DataPointState newState(dpValue, time(NULL), TA_Base_Bus::QUALITY_GOOD_NO_SPECIFIC_REASON);
                        liveDp->updateFieldState(newState);
                    }

                    if (musicDp)
                    {
                        TA_Base_Bus::DpValue dpValue(musicDp->getDataPointDataType(),
                                                     musicDp->getEnumLabelsMap(),
                                                     musicDp->getBooleanLabels());
                        dpValue.setBoolean(isMusic);
                        TA_Base_Bus::DataPointState newState(dpValue, time(NULL), TA_Base_Bus::QUALITY_GOOD_NO_SPECIFIC_REASON);
                        musicDp->updateFieldState(newState);
                    }

                    if (cyclicDp)
                    {
                        TA_Base_Bus::DpValue dpValue(cyclicDp->getDataPointDataType(),
                                                     cyclicDp->getEnumLabelsMap(),
                                                     cyclicDp->getBooleanLabels());
                        dpValue.setBoolean(isCyclic);
                        TA_Base_Bus::DataPointState newState(dpValue, time(NULL), TA_Base_Bus::QUALITY_GOOD_NO_SPECIFIC_REASON);
                        cyclicDp->updateFieldState(newState);
                    }
                }

                if (isNeedUpdateStatus || m_initialThread) // TD17013
                {
                    // update status datapoint
                    TA_Base_Bus::DataPoint* statusDp = m_cachedMapsInstance->getStatusDataPointFromZoneId(absoluteZoneId);

                    if (statusDp)
                    {
                        // PA Zone datapoint exists, so we can update it
                        TA_Base_Bus::DpValue dpValue(statusDp->getDataPointDataType(),
                                                     statusDp->getEnumLabelsMap(),
                                                     statusDp->getBooleanLabels());

                        dpValue.setBoolean(status);

                        // set up DataPointState with the default timestamp and quality
                        TA_Base_Bus::DataPointState newState(dpValue, time(NULL), TA_Base_Bus::QUALITY_GOOD_NO_SPECIFIC_REASON);

                        statusDp->updateFieldState(newState);
                    }
                }

                //  Maochun Sun++
                //  TD13410
                /*
                //  TD 10318.3 alanb: do not display priority number for "live" broadcasts
                if (isLive)
                {
                continue;
                }
                */
                //  ++Maochun Sun
                //  TD13410

                if (isNeedUpdatePriority || m_initialThread) // TD17013
                {
                    // update priority datapoint
                    TA_Base_Bus::DataPoint* priorityDp = m_cachedMapsInstance->getPriorityDataPointFromZoneId(absoluteZoneId);

                    if (priorityDp)
                    {
                        // PA Zone datapoint exists, so we can update it
                        TA_Base_Bus::DpValue dpValue(priorityDp->getDataPointDataType(),
                                                     priorityDp->getEnumLabelsMap(),
                                                     priorityDp->getBooleanLabels());

                        dpValue.setFloat(priority, priorityDp->getPrecision());

                        // set up DataPointState with the default timestamp and quality
                        TA_Base_Bus::DataPointState newState(dpValue, time(NULL), TA_Base_Bus::QUALITY_GOOD_NO_SPECIFIC_REASON);

                        priorityDp->updateFieldState(newState);
                    }
                }
            } // for zoneId
        } // for stationId

        // jeffrey++ Bug457

        // TD17013
        m_initialThread = false;
        // TD17013

        m_readIndex++;
        // ++jeffrey Bug457

        m_readWait.broadcast();
    }

    // TD16749

    // ++ Bug456
    void Table1200::readTimedWait()
    {
        m_readWait.timedWait(CachedConfig::getInstance()->getFastPollRateInMSecs());
    }

    // ++ Bug456

    ZoneStatus Table1200::getZoneStatus(unsigned int zoneId, unsigned int stationId)
        //throw ( TA_Base_Core::PasConnectionException )
    {
        TA_ASSERT(zoneId > 0 && zoneId <= MAXZONEID, "zoneId is out of range");
        TA_ASSERT(stationId > 0 && stationId <= MAXSTNID, "stationId is out of range");

        // ++ Bug456
        //m_readWait.timedWait( CachedConfig::getInstance()->getFastPollRateInMSecs() );
        // ++ Bug456

        ThreadGuard guard(m_lock);

        return m_stationStatuses[stationId - 1][zoneId - 1];
    }

    void invalidateDataPoint(TA_Base_Bus::DataPoint& datapoint);

    void Table1200::invalidateAllDataPoints()
    {
        LOG_SCOPE("Table1200::invalidateAllDataPoints");

        unsigned long absoluteZoneId = 1;

        for (int stationId = 0; stationId < MAXSTNID; ++stationId)
        {
            for (int zoneId = 0; zoneId < MAXZONEID; ++zoneId, ++absoluteZoneId)
            {
                try
                {
                    TA_Base_Bus::DataPoint* liveDp   = m_cachedMapsInstance->getLiveDataPointFromZoneId(absoluteZoneId);

                    if (liveDp)
                    {
                        invalidateDataPoint(*liveDp);
                    }

                    TA_Base_Bus::DataPoint* musicDp  = m_cachedMapsInstance->getMusicDataPointFromZoneId(absoluteZoneId);

                    if (musicDp)
                    {
                        invalidateDataPoint(*musicDp);
                    }

                    TA_Base_Bus::DataPoint* cyclicDp = m_cachedMapsInstance->getCyclicDataPointFromZoneId(absoluteZoneId);

                    if (cyclicDp)
                    {
                        invalidateDataPoint(*cyclicDp);
                    }

                    TA_Base_Bus::DataPoint* statusDp = m_cachedMapsInstance->getStatusDataPointFromZoneId(absoluteZoneId);

                    if (statusDp)
                    {
                        invalidateDataPoint(*statusDp);
                    }

                    TA_Base_Bus::DataPoint* priorityDp = m_cachedMapsInstance->getPriorityDataPointFromZoneId(absoluteZoneId);

                    if (priorityDp)
                    {
                        invalidateDataPoint(*priorityDp);
                    }
                }
                catch (...)
                {
                    // Carry on
                }
            }
        }
    }

    ReadTable1200::ReadTable1200(Table1200& table,
                                 TA_IRS_Bus::Scheduler& socketScheduler,
                                 TA_IRS_Bus::Scheduler& processScheduler,
                                 IPasEventSource& eventSource)
        : PASReadEvent(socketScheduler, processScheduler, eventSource)
        , m_table(table)
    {
    }

    ReadTable1200::ReadTable1200(ACE_Time_Value expiryTime,
                                 Table1200& table,
                                 TA_IRS_Bus::Scheduler& socketScheduler,
                                 TA_IRS_Bus::Scheduler& processScheduler,
                                 IPasEventSource& eventSource)
        : PASReadEvent(expiryTime, socketScheduler, processScheduler, eventSource)
        , m_table(table)
    {
    }

    void ReadTable1200::readTable()
    {
        LOG_SCOPE("ReadTable1200::readTable");

        ThreadGuard guard(m_table.m_lock);
        PASConnection::getInstance()->readTable(m_table.TABLE_NUMBER,
                                                m_table.m_buffer,
                                                m_table.BUFFER_SIZE);

        m_socketScheduler.post(new ReadTable1200(getNextTimeToExpire(),
                                                 m_table,
                                                 m_socketScheduler,
                                                 m_processScheduler,
                                                 m_pasEventSource));

        m_processScheduler.post(new ProcessTable1200(m_table));
    }

    ProcessTable1200::ProcessTable1200(Table1200& table)
        : m_table(table)
    {
    }

    void ProcessTable1200::consume()
    {
        LOG_SCOPE("ProcessTable1200::consume");

        m_table.processRead();
        PasTableReadCounter::instance().increase(m_table.TABLE_NUMBER);

        delete this;
    }

    void ProcessTable1200::cancel()
    {
        LOG_SCOPE("ProcessTable1200::cancel");
        delete this;
    }

    InvalidateTable1200::InvalidateTable1200(Table1200& table)
        : m_table(table)
    {
    }

    void InvalidateTable1200::consume()
    {
        LOG_SCOPE("InvalidateTable1200::consume");

        m_table.invalidateAllDataPoints();

        delete this;
    }

    void InvalidateTable1200::cancel()
    {
        LOG_SCOPE("InvalidateTable1200::cancel");
        delete this;
    }
}
