/**
 * The source code in this file is the property of
 * Ripple Systems and is not for redistribution
 * in any form.
 *
 * Source:   $File: //depot/C830AR_TIP/C830AR/transactive/app/pa/PAAgent/src/Table1201.cpp $
 * @author:  Ripple
 * @version: $Revision: #5 $
 *
 * Last modification: $DateTime: 2025/02/14 12:19:11 $
 * Last modified by:  $Author: limin.zhu $
 *
 */
 ///////////////////////////////////////////////////////////
 //
 //  Table1201.cpp
 //  Implementation of the Class Table1201
 //  Generated by Enterprise Architect
 //  Created on:      25-Sep-2003 18:53:34
 //  Original author:
 //
 ///////////////////////////////////////////////////////////
 //  Modification history:
 //
 //
 ///////////////////////////////////////////////////////////

#include "pch.h"
#include "Table1201.h"
#include "PasHelpers.h"
#include "PasTableManager.h"
#include "PASConnection.h"
#include "core/utilities/src/TAAssert.h"
#include "core/utilities/src/DebugUtilEx.h"
#include <ace/ACE.h>

using namespace TA_Base_Core;

const size_t TABLE_1201_SOURCE_ID_OFFSET        = 0;
const size_t TABLE_1201_ANNOUNCE_ID_OFFSET      = 1;
const size_t TABLE_1201_GLOBAL_COVERAGE_OFFSET  = 2;

namespace TA_IRS_App
{
    // ExceptionChecked
    Table1201::Table1201(TA_IRS_Bus::Scheduler& socketScheduler,
                         TA_IRS_Bus::Scheduler& processScheduler,
                         IPasEventSource& eventSource)
        : AbstractWriteablePASTable(1201)
        , m_socketScheduler(socketScheduler)
        , m_processScheduler(processScheduler)
        , m_pasEventSource(eventSource)
    {
        FUNCTION_ENTRY("Constructor");
        FUNCTION_EXIT;
    }

    void Table1201::setTableDataAndWrite(CORBA::Octet sourceId,
                                         CORBA::Octet announceId,
                                         const TA_Base_Bus::IPAAgentCorbaDef::ZoneCoverage& zones)
        //throw ( TA_Base_Core::PasWriteErrorException, TA_Base_Core::PasConnectionException )
    {
        LOG_SCOPE("Table1201::setTableDataAndWrite");

        ACE_Future<int> future;
        WriteTable1201* event = new WriteTable1201(*this,
                                                   future,
                                                   sourceId,
                                                   announceId,
                                                   zones,
                                                   m_socketScheduler,
                                                   m_processScheduler,
                                                   m_pasEventSource);
        addWriteEvent(*event);
        m_socketScheduler.post(event);

        int retVal = -1;
        ACE_Time_Value tv(10, 0);
        tv += ACE_OS::gettimeofday();

        if (-1 == future.get(retVal, &tv))
        {
            char msg[100] = {0};
            sprintf(msg, "Timeout on write operation on table %d", TABLE_NUMBER);
            TA_THROW(TA_Base_Core::PasWriteErrorException(retVal, msg));
        }

        if (retVal)
        {
            char msg[100] = {0};
            sprintf(msg, "Write operation on table %d returned an error state %d", TABLE_NUMBER, retVal);
            TA_THROW(TA_Base_Core::PasWriteErrorException(retVal, msg));
        }
    }

    WriteTable1201::WriteTable1201(Table1201& table,
                                   ACE_Future<int>& future,
                                   CORBA::Octet sourceId,
                                   CORBA::Octet announceId,
                                   const TA_Base_Bus::IPAAgentCorbaDef::ZoneCoverage& zones,
                                   TA_IRS_Bus::Scheduler& socketScheduler,
                                   TA_IRS_Bus::Scheduler& processScheduler,
                                   IPasEventSource& eventSource)
        : PASWriteEvent(table, future, socketScheduler, processScheduler, eventSource)
        , m_table(table)
        , m_sourceId(sourceId)
        , m_announceId(announceId)
        , m_zones(zones)
    {
    }

    WriteTable1201::WriteTable1201(ACE_Time_Value timeToExpire,
                                   Table1201& table,
                                   ACE_Future<int>& future,
                                   CORBA::Octet sourceId,
                                   CORBA::Octet announceId,
                                   const TA_Base_Bus::IPAAgentCorbaDef::ZoneCoverage& zones,
                                   TA_IRS_Bus::Scheduler& socketScheduler,
                                   TA_IRS_Bus::Scheduler& processScheduler,
                                   IPasEventSource& eventSource)
        : PASWriteEvent(timeToExpire, table, future, socketScheduler, processScheduler, eventSource)
        , m_table(table)
        , m_sourceId(sourceId)
        , m_announceId(announceId)
        , m_zones(zones)
    {
    }

    void WriteTable1201::writeTable()
    {
        LOG_SCOPE("WriteTable1201::writeTable");

        // Need a buffer for PA_MAXSTNID x 32bits
        std::uint32_t* globalCoverageBitmaps = reinterpret_cast<std::uint32_t*>(::calloc(TA_Base_Bus::IPAAgentCorbaDef::PA_MAXSTNID, 4));

        PasHelpers::instance().coverageToGlobalCoverageBitmaps(m_zones, globalCoverageBitmaps);

        // ReEntrant as this will also be guarded in the write() call.
        ThreadGuard guard(m_table.m_lock);

        PasHelpers::instance().set8bit(m_table.m_buffer, TABLE_1201_SOURCE_ID_OFFSET, m_sourceId);
        PasHelpers::instance().set8bit(m_table.m_buffer, TABLE_1201_ANNOUNCE_ID_OFFSET, m_announceId);

        unsigned long offset = TABLE_1201_GLOBAL_COVERAGE_OFFSET;

        for (int stationId = 1; stationId <= TA_Base_Bus::IPAAgentCorbaDef::PA_MAXSTNID; ++stationId)
        {
            auto coverage = globalCoverageBitmaps[stationId - 1];

            if (AbstractPASTable::is_bgm(m_sourceId))
            {
                coverage = UINT32_MAX;
            }

            PasHelpers::instance().set32bit(m_table.m_buffer, offset, coverage);
            offset += 4;
        }

        ::free(globalCoverageBitmaps);
        globalCoverageBitmaps = NULL;

        m_future.set(PASConnection::getInstance()->writeTable(m_table.TABLE_NUMBER,
                                                              m_table.m_buffer,
                                                              m_table.BUFFER_SIZE));
    }

    PASWriteEvent* WriteTable1201::recreateEvent(ACE_Time_Value timeToExpire)
    {
        return new WriteTable1201(timeToExpire,
                                  m_table,
                                  m_future,
                                  m_sourceId,
                                  m_announceId,
                                  m_zones,
                                  m_socketScheduler,
                                  m_processScheduler,
                                  m_pasEventSource);
    }
}
